heroes/urls.py
from django.conf.urls import patterns, url
from heroes import views

urlpatterns = patterns('',
        url(r'^$', views.ability_index, name='index'),
        url(r'^(?P<id>\d+)/$', views.ability_detail, name='detail'),
        url(r'^new/$', views.ability_new, name='new'),
        url(r'^edit/(?P<id>\d+)/$', views.ability_edit, name='edit'),
        url(r'^save/(?P<id>\d+)/$', views.ability_save, name='save'),
        url(r'^ask_del/(?P<id>\d+)/$', views.ability_ask_del, name='ask_del'),
        url(r'^delete/(?P<id>\d+)/$', views.ability_delete, name='delete'),
    )

heroes_lib/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import heroes.urls

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'heroes_lib.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^abilities/', include(heroes.urls, namespace='abilities'))
)

heroes/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Ability(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255, default='No Description.')
    # TODO: Добавить поле с изображением

    def __unicode__(self):
        return self.name

heroes/views.py
from django.shortcuts import render
from heroes.models import Ability
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import Context, loader
from django.core.urlresolvers import reverse

def ability_index(request):
    abilities = Ability.objects.all()
    context = {'abilities': abilities}
    return render(request, 'abilities/index.html', context)

def ability_detail(request, id):
    ability = Ability.objects.filter(pk=id).first()

    if not ability:
        raise Http404

    context = {'ability': ability}
    return render(request, 'abilities/detail.html', context)

def ability_new(request):
    ability = Ability.objects.create()
    context = {
        'is_new': True,
        'ability': ability,
        'title': 'Creating New Ability',
    }

    return render(request, 'abilities/edit.html', context)

def ability_edit(request, id):
    ability = Ability.objects.filter(pk=id).first()
    title = 'Edit of "%s"' % ability.name

    if not ability:
        raise Http404

    context = {
        'is_new': False,
        'ability': ability,
        'title': title
        }
    return render(request, 'abilities/edit.html', context)

def ability_save(request, id):
    ability = Ability(
        id=id,
        name=request.POST['name'],
        description=request.POST['description']
    )
    ability.save()
    return HttpResponseRedirect(reverse('abilities:index'))

def ability_ask_del(request, id):
    ability = Ability.objects.filter(pk=id).first()

    if not ability:
        raise Http404

    context = {
        'ability': ability
    }

    return render(request, 'abilities/delete.html', context)

def ability_delete(request, id):
    Ability.objects.filter(pk=id).delete()
    return HttpResponseRedirect(reverse('abilities:index'))

heroes/templates/abilities/delete.html
<html>
    <head>
        <title>
            Delete
        </title>
    </head>
    <body>
        <h2>
            Are you sure you want to delete "{{ability.name}}"?
        </h2>
        <form action="{% url 'abilities:delete' ability.id %}" method="post">
            {% csrf_token %}
            <dl>
                <dt>
                    Name:
                </dt>
                <dd>
                    {{ability.name}}
                </dd>
                <dt>
                    Description
                </dt>
                <dd>
                    {{ability.description}}
                </dd>
            </dl>
            <input type="submit" value="Delete" />
        </form>
    </body>
</html>

heroes/templates/abilities/detail.html
<html>
    <head>
        <title>
            {{ability.name}}
        </title>
    </head>
    <body>
        <h2>
            {{ability.name}}
        </h2>
        <p>
            {{ability.description}}
        </p>
    </body>
</html>

heroes/templates/abilities/edit.html
<html>
    <head>
        <title>
            {{title}}
        </title>
    </head>
    <body>
        <h2>
            {{title}}
        </h2>
        <form action="{% url 'abilities:save' ability.id %}" method="post">
            {% csrf_token %}
            <dl>
                <dt>
                    Name:
                </dt>
                <dd>
                    <input type="text" name="name" value="{{ability.name}}" />
                </dd>
                <dt>
                    Description
                </dt>
                <dd>
                    <input type="text" name="description" value="{{ability.description}}"/>
                </dd>
            </dl>
            <input type="submit" value="Save" />
        </form>
    </body>
</html>

heroes/templates/abilities/index.html
{% if abilities %}
    <h3>
        Abilities List:
    </h3>
    <table>
        {% for a in abilities %}
            <tr>
                <td>
                    {{a.name}}
                </td>
                <td>
                    <a href="{% url 'abilities:detail' a.id %}">
                        Show
                    </a>
                </td>
                <td>
                    <a href="{% url 'abilities:edit' a.id %}">
                        Edit
                    </a>
                </td>
                <td>
                    <a href="{% url 'abilities:ask_del' a.id %}">
                        Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>
        No abilities are available!
    </h3>
    <p>
        Nothing to show.
    </p>
{% endif %}
<a href="{% url 'abilities:new' %}">Create New Ability!</a>